### PR TITLE
Ready 0.6.0

### PR DESCRIPTION
**Pull request by LionOps**

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by thomasw** [comment]
:+1:  Let's not be afraid to go to 1.0 at some point. This library seems pretty stable.

**Comment by LionOps** [comment]
> Let's not be afraid to go to 1.0 at some point. This library seems pretty stable.

I was debating it on this PR. Let me open a new PR since it's unlikely to change.

**Comment by LionOps** [comment]
Replaced by https://github.com/yola/pixabayjs/pull/35

**Pull request closed without merging**
