### PR TITLE
Report the page requested with a bad response

### PR DESCRIPTION
**Pull request by LionOps**
-- Includes some test cleanup

### CODE REVIEW

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by kahnvex** [comment]
What will a consumer use this for?

**Comment by LionOps** [comment]
A consumer can check the error message, and if the invalid range error, know what page was requested.

**Comment by kahnvex** [comment]
> know what page was requested

Why do they need to know this? Isn't it better to tell them in all requests which page is the last one?

**Comment by LionOps** [comment]
> Why do they need to know this? Isn't it better to tell them in all requests which page is the last one?

Certainly, but the current architecture doesn't support that. The ResultList object would need that information, but after `next` is called, it's not interacted with again for that request. ResultList `next` calls the Retriever's `get` method, and the response is handed to ResponseHandler before given to the consumer.

We agreed it was the consumer's responsibility for handling multiple simultaneous requests. They get back `totalHits` and would know how many hits there are per page.

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by snitch** [comment]
:sparkles: No lint errors found. :sparkles:

**Comment by kahnvex** [comment]
:+1:

**Pull request merged**
